var wingStyleGuide = {
	"Air Combat Command":"ACC",
	"Air Command and Staff College":"ACSC",
	"Active Duty":"AD",
	"Air Expeditionary Force":"AEF",
	"Air Education and Training Command":"AETC",
	"Air Force":"AF",
	"Air Force Base":"AFB",
	"Air Force Global Strike Command":"AFGSC",
	"Air Force Instruction":"AFI",
	"Air Force Materiel Command":"AFMC",
	"Air Force Reserve Component":"AFRC",
	"Air Force Space Command":"AFSPC",
	"Air Force Special Operations Command":"AFSOC",
	"Air Force Specialty Code":"AFSC",
	"Active Guard Reserve":"AGR",
	"Assignment Management System":"AMS",
	"Air Mobility Command":"AMC",
	"Air National Guard":"ANG",
	"Airman Leadership School":"ALS",
	"Air Operations Center":"AOC",
	"Area of Operations":"AOR",
	"AEF UTC Reporting Tool":"ART",
	"As Soon As Possible":"ASAP",
	"Air Tasking Order":"ATO",
	"Air War College":"AWC",
	"Below Promotion Zone":"BTZ",
	"Command and Control":"C2",
	"Common Access Card":"CAC",
	"Combat Air Force":"CAF",
	"Chemical, Biological, Radiological, Nuclear and Explosive":"CBRNE",
	"Commander":"CC",
	"Community College of the Air Force":"CCAF",
	"Inspector General":"IG",
	"Combatant Commander":"CCDR",
	"Combatant Command":"CCMD",
	"Combined Forces Air Component Commander":"CFACC",
	"Company Grade Office":"CGO",
	"Central Intelligence Agency":"CIA",
	"Chairman of the Joint Chiefs of Staff":"CJCS",
	"Chief Master Sergeant, US Air Force":"CMSAF",
	"Cource of Action":"COA",
	"Combatant Command (Authority)":"COCOM",
	"Concept of Operations":"CONOP",
	"Continental United States":"CONUS",
	"Chief of Staff, US Air Force":"CSAF",
	"Commander's Support Staff":"CSS",
	"Counterterrorism":"CT",
	"Director of Operations":"DO",
	"Department of Defense":"DoD",
	"Direct Reporting Unit":"DRU",
	"Distinguised Visitor":"DV",
	"Enlisted Performance Report":"EPR",
	"Explosive Ordinance Disposal":"EOD",
	"Federal Bureau of Investigation":"FBI",
	"Force Protection Condition":"FPCON",
	"Field Grade Officer":"FGO",
	"First Term Airman Center":"FTAC",
	"Global Positioning Satellite":"GPS",
	"Geographically Seperated Unit":"GSU",
	"Government Travel Card":"GTC",
	"Headquarters Air Force":"HAF",
	"Hazardous Material":"HAZMAT",
	"Higher Headquarters":"HHQ",
	"In Accordance With":"IAW",
	"Intermediate Developemental Education":"IDE",
	"Individual Mobilization Augmentee":"IMA",
	"In support of":"ISO",
	"Intelligence, Surveillance and Reconnaissance":"ISR",
	"Joint Chiefs of Staff":"JCS",
	"Joint Forces Air Component Commander":"JFACC",
	"Joint Task Force":"JTF",
	"Judge Advocate General":"JAG",
	"Killed in Action":"KIA",
	"Limiting Factor":"LIMFAC",
	"Law of Armed Conflict":"LOAC",
	"Major Command":"MAJCOM",
	"Missing in Action":"MIA",
	"Military Construction":"MILCON",
	"Managment Level Review":"MLR",
	"Memorandum of Agreement":"MOA",
	"Morale, Welfare, and Recreation":"MWR",
	"Numbered Air Force":"NAF",
	"North Atlantic Treaty Organization":"NATO",
	"Noncommissioned Officer":"NCO",
	"Noncommissioned Officer Academy":"NCOA",
	"Noncommissioned Officer in-charge":"NCOIC",
	"Non-classified Internet Protocol Router":"NIPR",
	"National Security Agency":"NSA",
	"Operation ENDURING FREEDOM":"OEF",
	"Operation Freedom sentinel":"OFS",
	"operating instruction":"OI",
	"Operation Iraqi Freedom":"OIF",
	"Operation plan":"OPLAN",
	"Operational Readiness Inspection":"ORI",
	"Occupational Safety and health administration":"OSHA",
	"Office of Special Investigations":"OSI",
	"Of the Quarter":"OTQ",
	"Of the Year":"OTY",
	"Public Affairs":"PA",
	"Pacific Air Forces":"PACAF",
	"Passengers":"PAX",
	"Permanent Change of Station":"PCS",
	"Primary Developmental Education":"PDE",
	"Physical fitness assessment":"PFA",
	"Professional Military Education":"PME",
	"Point of contact":"POC",
	"President of the United States":"POTUS",
	"Prisoner of war":"POW",
	"Quality Assurance":"QA",
	"Quality Control":"QC",
	"Quality of life":"QoL",
	"Rules of engagment":"ROE",
	"Reserve Officer Training Corps":"ROTC",
	"Sexual Assault Prevention and Response":"SARP",
	"Sexual Assault Response Coordinator":"SARC",
	"Staff Assistance Visit":"SAV",
	"Senior Developmental Education":"SDE",
	"Secretary of Defense":"SecDef",
	"Secretary of the Air Force":"SecAF",
	"Staff Judge Advocate":"SJA",
	"Senior NCO Academy":"SNCOA",
	"Senior NCO":"SNCO",
	"Special Operations Forces":"SOF",
	"Squadron Officer School":"SOS",
	"Standard Operating Procedures":"SOP",
	"Subject Matter Expert":"SME",
	"Temporary Duty":"TDY",
	"Tactics, Techniques and Procedures":"TTPs",
	"Unmanned Aerial Vehicle":"UAV",
	"Unit Compliance Inspection":"UCI",
	"Uniform Code of Military Justice":"UCMJ",
	"Unit Effectiveness Inspection":"UEI",
	"Unfavorable Information File":"UIF",
	"United States Air Forces Europe":"USAFE",
	"US Coast Guard":"USCG",
	"US African Command":"USAFRICOM",
	"US Central Command":"USCENTCOM",
	"US Cyberspace Command":"USCYBERCOM",
	"US European Command":"USEUCOM",
	"US Indo-Pacific Command":"USINDOPACOM",
	"US Northern Command":"USNORTHCOM",
	"US Special Operations Command":"USSOCOM",
	"US Southern Command":"USSOUTHCOM",
	"US Strategic Commands":"USSTRATCOM",
	"US Transportation Command":"USTRANSCOM",
	"Us Marine Corps":"USMC",
	"US Navy":"USN",
	"Very Important Person":"VIP",
	"Vice President of the United States":"VPOTUS",
	"Weapons of Mass Destruction":"WMD",
	"First Sergeant":"1st Sgt",
	"Acquisition":"acq",
	"additional":"add'l",
	"administration":"admin",
	"advance":"adv",
	"Afghanistan":"Afg",
	"aircraft":"acft",
	"Airmen":"Amn",
	"Airman":"Amn",
	"Airfield":"afld",
	"amplified":"amp'd",
	"appointments":"appts",
	"attention":"attn",
	"average":"avg",
	"award":"awd",
	"billion":"B",
	"board":"brd",
	"brief":"brf",
	"building":"bldg",
	"capability":"cape",
	"center":"ctr",
	"certication":"cert",
	"checklist":"chklst",
	"civilian":"civ",
	"combat":"cmbt",
	"command":"cmd",
	"committee":"cmte",
	"communication":"comm",
	"complied with":"c/w",
	"conference":"conf",
	"configuration":"config",
	"control":"ctrl",
	"coordinate":"coord",
	"coordinated":"coord'd",
	"course":"crs",
	"critical":"crit",
	"decoration":"dec",
	"delivered":"del'd",
	"deployed":"dply'd",
	"develop":"dev",
	"developed":"dev'd",
	"development":"devmnt",
	"distribution":"distro",
	"division":"div",
	"enlisted":"enl",
	"equip":"eqp",
	"established":"est'd",
	"estimate":"est",
	//"estimated":"est'd",
	"executed":"exec'd",
	"exercise":"exer",
	"evacuation":"evac",
	"evaluation":"eval",
	"exhanges":"exchgs",
	"feet":"ft",
	"financial plan":"fin plan",
	"flight":"flt",
	"forward":"fwd",
	"frequency":"freq",
	"generation":"gen",
	"government":"gov't",
	"group":"gp",
	"high":"hi",
	"high-visibilty":"hi-vis",
	"hours":"hrs",
	"indentified":"ID'd",
	"include":"incl",
	"increase":"incr",
	"indoctrination":"indoc",
	"information":"info",
	"intelligence":"intel",
	"intelligence community":"intel cmty",
	"inspection":"insp",
	"instruction":"instr",
	"international":"int'l",
	"joint":"jt",
	"kilometer":"k",
	"large":"lg",
	"largest":"lgst",
	"leader":"ldr",
	"leadership":"ldrshp",
	"level":"lvl",
	"location":"loc",
	"maintenance":"mx",
	"manage":"mng",
	"management":"mgmt",
	"maximized":"max'd",
	"medical evacuation":"medevac",
	"meeting":"mtg",
	"member":"mbr",
	"message":"msg",
	"military":"mil",
	"mile":"mi",
	"million":"M",
	"minute":"min",
	"mission":"msn",
	"month":"mo",
	"multinational":"multinat'l",
	"national":"nat'l",
	"network":"ntwk",
	"nominee":"nom",
	"objective":"obj",
	"officer":"ofcr",
	"operations":"ops",
	"organization":"org",
	"package":"pkg",
	"personnel":"prsnl",
	"prepare":"prep",
	"previous":"prev",
	"priority":"pri",
	"primary":"pri",
	"problem":"prob",
	"products":"prod",
	"professional":"prof",
	"program":"prgm",
	"project":"proj",
	"publication":"pub",
	"qualification":"qual",
	"quarter":"qtr",
	"rating":"rtg",
	"ready":"rdy",
	"received":"rcv'd",
	"reorganize":"reorg",
	"report":"rpt",
	"representative":"rep",
	"requirement":"rqmnt",
	"resposible":"resp",
	"security":"sec",
	"selected":"sel'd",
	"service":"svc",
	"squadron":"sq",
	"standard":"std",
	"standardization and evaluation":"stan/eval",
	"support":"spt",
	"synchronize":"sync",
	"system":"sys",
	"target":"tgt",
	"team":"tm",
	"technical":"tech",
	"threat":"thrt",
	"thousand":"K",
	"training":"trng",
	"visibility":"vis",
	"volunteer":"vol",
	"weapon":"wpn",
	"weekly":"wkly",
	"wing":"wg",
	"working group":"wrkng gp",
	"year":"yr"
}

